plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

group 'com.mad.musicplayer'
version '1.0'

sourceCompatibility = '17'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.xerial:sqlite-jdbc:3.49.1.0'
}

javafx {
    version = '21.0.1'
    modules = ['javafx.controls', 'javafx.media']
}

application {
    mainClass = 'gui.Main'
}
